/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculatorapp;

/**
 *
 * @author x20366351
 */
public class CalculatorGUI extends javax.swing.JFrame {
    double num1, num2;
    /**
     * Creates new form CalculatorGUI
     */
    public CalculatorGUI() {
        num1 = 0;
        num2 = 0;
        initComponents();
        divideBtn.setVisible(false);
        multiplyBtn.setVisible(false);
        modulusBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeGrp = new javax.swing.ButtonGroup();
        titleLbl = new javax.swing.JLabel();
        basicRB = new javax.swing.JRadioButton();
        advancedRB = new javax.swing.JRadioButton();
        num1Lbl = new javax.swing.JLabel();
        num2Lbl = new javax.swing.JLabel();
        num1TF = new javax.swing.JTextField();
        num2TF = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        subtractBtn = new javax.swing.JButton();
        divideBtn = new javax.swing.JButton();
        multiplyBtn = new javax.swing.JButton();
        modulusBtn = new javax.swing.JButton();
        ansLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titleLbl.setText("Calculator Application");

        typeGrp.add(basicRB);
        basicRB.setText("Basic");
        basicRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicRBActionPerformed(evt);
            }
        });

        typeGrp.add(advancedRB);
        advancedRB.setText("Advanced");
        advancedRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advancedRBActionPerformed(evt);
            }
        });

        num1Lbl.setText("Number 1:");

        num2Lbl.setText("Number 2:");

        num1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1TFActionPerformed(evt);
            }
        });

        num2TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2TFActionPerformed(evt);
            }
        });

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        subtractBtn.setText("Substract");
        subtractBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractBtnActionPerformed(evt);
            }
        });

        divideBtn.setText("Divide");
        divideBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideBtnActionPerformed(evt);
            }
        });

        multiplyBtn.setText("Multiply");
        multiplyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyBtnActionPerformed(evt);
            }
        });

        modulusBtn.setText("Modulus");
        modulusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulusBtnActionPerformed(evt);
            }
        });

        ansLbl.setText("Answer: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLbl)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(num2Lbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(num2TF))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(num1Lbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(num1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(basicRB)
                                    .addComponent(advancedRB)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(divideBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(addBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(subtractBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(multiplyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addComponent(modulusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ansLbl))))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basicRB)
                    .addComponent(num1Lbl)
                    .addComponent(num1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(advancedRB)
                    .addComponent(num2Lbl)
                    .addComponent(num2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(subtractBtn))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(divideBtn)
                    .addComponent(multiplyBtn)
                    .addComponent(modulusBtn))
                .addGap(18, 18, 18)
                .addComponent(ansLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void basicRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicRBActionPerformed
        // TODO add your handling code here:
        divideBtn.setVisible(false);
        multiplyBtn.setVisible(false);
        modulusBtn.setVisible(false);
    }//GEN-LAST:event_basicRBActionPerformed

    private void advancedRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advancedRBActionPerformed
        // TODO add your handling code here:
        divideBtn.setVisible(true);
        multiplyBtn.setVisible(true);
        modulusBtn.setVisible(true);
    }//GEN-LAST:event_advancedRBActionPerformed

    private void num1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num1TFActionPerformed

    private void num2TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num2TFActionPerformed

    private void divideBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideBtnActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(num1TF.getText());
        num2 = Double.parseDouble(num2TF.getText());
        ansLbl.setText(" " + (num1/num2));
    }//GEN-LAST:event_divideBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        //You have to parse if it is not a String
        num1 = Double.parseDouble(num1TF.getText());
        num2 = Double.parseDouble(num2TF.getText());
        ansLbl.setText(" " + (num1+num2));
    }//GEN-LAST:event_addBtnActionPerformed

    private void subtractBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractBtnActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(num1TF.getText());
        num2 = Double.parseDouble(num2TF.getText());
        ansLbl.setText(" " + (num1 - num2));
    }//GEN-LAST:event_subtractBtnActionPerformed

    private void multiplyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyBtnActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(num1TF.getText());
        num2 = Double.parseDouble(num2TF.getText());
        ansLbl.setText(" " + (num1 * num2));
    }//GEN-LAST:event_multiplyBtnActionPerformed

    private void modulusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulusBtnActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(num1TF.getText());
        num2 = Double.parseDouble(num2TF.getText());
        ansLbl.setText(" " + (num1%num2));
    }//GEN-LAST:event_modulusBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JRadioButton advancedRB;
    private javax.swing.JLabel ansLbl;
    private javax.swing.JRadioButton basicRB;
    private javax.swing.JButton divideBtn;
    private javax.swing.JButton modulusBtn;
    private javax.swing.JButton multiplyBtn;
    private javax.swing.JLabel num1Lbl;
    private javax.swing.JTextField num1TF;
    private javax.swing.JLabel num2Lbl;
    private javax.swing.JTextField num2TF;
    private javax.swing.JButton subtractBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.ButtonGroup typeGrp;
    // End of variables declaration//GEN-END:variables
}
